spring:
  profiles:
    active: give_blue_server
    group:
      local: local, common, secret
      give_blue_server: give_blue, common, secret
      give_green_server: give_green, common, secret

server:
  env: give_blue

---

# Local 환경
spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
  deploy-address: localhost
  name: local

---

# GIVE BLUE 서버
spring:
  config:
    activate:
      on-profile: give_blue

server:
  port: 8001
  deploy-address: give-portfolio.shop
  name: give_blue
  env: give_blue

---

# GIVE GREEN 서버
spring:
  config:
    activate:
      on-profile: give_green

server:
  port: 8002
  deploy-address: give-portfolio.shop
  name: give_green
  env: give_green

---

# 공통 설정
spring:
  config:
    activate:
      on-profile: common

  security:
    oauth2:
      client:
        registration:

          google:
            client-name: Google
            scope:
              - email
              - profile
            redirect-uri: https://give-portfolio.shop/login/oauth2/code/google

          naver:
            client-name: Naver
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            redirect-uri: https://give-portfolio.shop/login/oauth2/code/naver

          kakao:
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            redirect-uri: https://give-portfolio.shop/login/oauth2/code/kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

client:
  deploy-address: give-portfolio.shop

mybatis:
  mapper-locations:
    - /mappers/*.xml
