#spring:
#  profiles:
#    active: local
#    group:
#      local: local, common, secret

spring:
  profiles:
    active: give_blue_server
    group:
      local: local, common, secret
      give_blue_server: give_blue, common, secret
      give_green_server: give_green, common, secret

server:
  env: give_blue
  sudo nano /home/ubuntu/nginx/default.conf

---

spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          naver:
            redirectUri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            redirectUri: http://localhost:8080/login/oauth2/code/kakao

server:
  port: 8080
  deploy-address: localhost
  name: local

---

# ============ GIVE - BLUE 서버 ============

spring:
  config:
    activate:
      on-profile: give_blue

server:
  port: 8001
  deploy-address: give-portfolio.shop
  name: give_blue
  env: give_blue

---

# ============ GIVE - GREEN 서버 ============
spring:
  config:
    activate:
      on-profile: give_green

server:
  port: 8002
  deploy-address: give-portfolio.shop
  name: give_green
  env: give_green

---

#spring:
#  config:
#    activate:
#      on-profile: common
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            scope:
#              - email
#              - profile
#          naver:
#            clientName: Naver
#            authorizationGrantType: authorization_code
#            clientAuthenticationMethod: POST
#          kakao:
#            clientName: Kakao
#            authorizationGrantType: authorization_code
#            clientAuthenticationMethod: POST
#        provider:
#          naver:
#            authorizationUri: https://nid.naver.com/oauth2.0/authorize
#            tokenUri: https://nid.naver.com/oauth2.0/token
#            userInfoUri: https://openapi.naver.com/v1/nid/me
#            userNameAttribute: response
#          kakao:
#            authorizationUri: https://kauth.kakao.com/oauth/authorize
#            tokenUri: https://kauth.kakao.com/oauth/token
#            userInfoUri: https://kapi.kakao.com/v2/user/me
#            userNameAttribute: id

spring:
  config:
    activate:
      on-profile: common

  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - email
              - profile

          naver:
            clientName: Naver
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: POST
            redirectUri: https://{client.deploy-address}/login/oauth2/code/naver

          kakao:
            clientName: Kakao
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: POST
            redirectUri: https://{client.deploy-address}/login/oauth2/code/kakao

        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response

          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

#client:
#  deploy-address: "localhost:3000"

client:
  deploy-address: give-portfolio.shop

mybatis:
  mapper-locations:
    - /mappers/*.xml